INSERT INTO products (id, nombre, precio, descripcion, img, stock, categoria) VALUES
(1, 'Tabla de corte de bambú', 18, 'Resistente y ecológica, ideal para una cocina moderna.', '1.jpg', 10, 'cocina'),
(2, 'Set de utensilios de madera', 24, 'Cocina con estilo natural todos los días.', '2.jpg', 10, 'cocina'),
(3, 'Frascos de vidrio hermético', 9, 'Mantén tus alimentos frescos y ordenados.', '3.jpg', 10, 'cocina'),
(4, 'Porta especias minimalista', 14, 'Organización práctica con diseño elegante.', '4.jpg', 10, 'cocina'),
(5, 'Tazas de cerámica', 12, 'Perfecta para disfrutar tu café favorito.', '5.jpg', 10, 'cocina'),
(6, 'Plato decorativo blanco', 15, 'Un toque limpio y moderno para tu mesa.', '6.jpg', 10, 'cocina'),
(7, 'Escurridor metálico', 22, 'Funcional y elegante para tu fregadero.', '7.jpg', 10, 'cocina'),
(8, 'Botella de vidrio reutilizable', 11, 'Ideal para hidratarte con estilo.', '8.jpg', 10, 'cocina'),
(9, 'Paños de cocina de algodón', 10, 'Suaves, prácticos y con diseño moderno.', '9.jpg', 10, 'cocina'),
(10, 'Bandeja de madera', 19, 'Perfecta para servir o decorar.', '10.jpg', 10, 'cocina'),
(11, 'Dispensador de jabón', 13, 'Dale un toque moderno a tu baño.', '3.jpg', 10, 'baño'),
(12, 'Porta cepillos de cerámica', 11, 'Orden y estilo en tu lavamanos.', '5.jpg', 10, 'baño'),
(13, 'Set de toallas blancas', 29, 'Suavidad y confort tipo hotel.', '8.jpg', 10, 'baño'),
(14, 'Bandeja organizadora', 14, 'Ideal para perfumes y accesorios.', '4.jpg', 10, 'baño'),
(15, 'Cortina de baño neutra', 21, 'Combina fácilmente con cualquier estilo.', '9.jpg', 10, 'baño'),
(16, 'Alfombra antideslizante', 18, 'Seguridad y comodidad al salir de la ducha.', '2.jpg', 10, 'baño'),
(17, 'Cesto para ropa', 26, 'Mantén el orden sin perder diseño.', '6.jpg', 10, 'baño'),
(18, 'Frasco de vidrio para algodón', 9, 'Pequeño detalle que marca la diferencia.', '3.jpg', 10, 'baño'),
(19, 'Porta papel higiénico', 15, 'Diseño simple y funcional.', '7.jpg', 10, 'baño'),
(20, 'Espejo redondo', 39, 'Aporta amplitud y elegancia.', '10.jpg', 10, 'baño'),
(21, 'Organizador de escritorio', 17, 'Mantén tu espacio limpio y ordenado.', '4.jpg', 10, 'oficina'),
(22, 'Lámpara LED de escritorio', 34, 'Iluminación ideal para trabajar o estudiar.', '8.jpg', 10, 'oficina'),
(23, 'Soporte para laptop', 29, 'Mejora tu postura mientras trabajas.', '2.jpg', 10, 'oficina'),
(24, 'Cuaderno minimalista', 12, 'Perfecto para notas y planificación.', '1.jpg', 10, 'oficina'),
(25, 'Portalápices metálico', 9, 'Diseño simple y funcional.', '4.jpg', 10, 'oficina'),
(26, 'Reloj de escritorio', 19, 'Controla tu tiempo con estilo.', '5.jpg', 10, 'oficina'),
(27, 'Mouse pad neutro', 8, 'Comodidad para largas jornadas.', '9.jpg', 10, 'oficina'),
(28, 'Archivador de cartón', 14, 'Organiza tus documentos fácilmente.', '6.jpg', 10, 'oficina'),
(29, 'Soporte para celular', 10, 'Ideal para videollamadas.', '3.jpg', 10, 'oficina'),
(30, 'Pizarra pequeña', 16, 'Visualiza tus tareas diarias.', '7.jpg', 10, 'oficina'),
(31, 'Jarrón de cerámica', 24, 'Un detalle elegante para cualquier espacio.', '10.jpg', 10, 'decoracion'),
(32, 'Vela aromática', 14, 'Crea un ambiente cálido y relajante.', '5.jpg', 10, 'decoracion'),
(33, 'Marco para fotos', 12, 'Resalta tus recuerdos favoritos.', '2.jpg', 10, 'decoracion'),
(34, 'Reloj de pared moderno', 29, 'Diseño limpio y actual.', '9.jpg', 10, 'decoracion'),
(35, 'Bandeja decorativa', 18, 'Versátil y sofisticada.', '4.jpg', 10, 'decoracion'),
(36, 'Planta artificial', 21, 'Toque verde sin mantenimiento.', '1.jpg', 10, 'decoracion'),
(37, 'Cojín decorativo', 19, 'Confort y estilo para tu sofá.', '8.jpg', 10, 'decoracion'),
(38, 'Figura decorativa', 16, 'Un detalle moderno y sutil.', '6.jpg', 10, 'decoracion'),
(39, 'Espejo decorativo', 34, 'Elegancia para cualquier pared.', '10.jpg', 10, 'decoracion'),
(40, 'Canasta de mimbre', 27, 'Orden con estilo natural.', '3.jpg', 10, 'decoracion'),
(41, 'Lámpara de mesa', 28, 'Iluminación cálida para tu descanso.', '5.jpg', 10, 'cuarto'),
(42, 'Juego de sábanas', 49, 'Suavidad que se siente al dormir.', '9.jpg', 10, 'cuarto'),
(43, 'Almohada ergonómica', 32, 'Descanso cómodo toda la noche.', '8.jpg', 10, 'cuarto'),
(44, 'Manta decorativa', 26, 'Calidez y estilo para tu cama.', '7.jpg', 10, 'cuarto'),
(45, 'Mesa de noche', 59, 'Funcional y moderna.', '6.jpg', 10, 'cuarto'),
(46, 'Organizador de clóset', 22, 'Aprovecha mejor tu espacio.', '4.jpg', 10, 'cuarto'),
(47, 'Espejo de piso', 69, 'Elegancia y amplitud visual.', '10.jpg', 10, 'cuarto'),
(48, 'Perchero minimalista', 24, 'Orden práctico y decorativo.', '2.jpg', 10, 'cuarto'),
(49, 'Cesto decorativo', 19, 'Ideal para ropa o mantas.', '3.jpg', 10, 'cuarto'),
(50, 'Cuadro decorativo', 29, 'Dale personalidad a tu habitación.', '9.jpg', 10, 'cuarto');
